### ISSUE TITLE
Error to start server

### ISSUE THREAD

**Issue by JoewAlabel** [Andreas1331/ragemp-roleplay#1]
The server get those errors (missing dlls) after started:

`Could not load file or assembly 'C:\GTARoleplay\server-files\dotnet\resources\GTARoleplay\netcoreapp3.1\Microsoft.EntityFrameworkCore.resources.dll'. The system cannot find the file specified.
Could not load file or assembly 'C:\GTARoleplay\server-files\dotnet\resources\GTARoleplay\netcoreapp3.1\Microsoft.EntityFrameworkCore.resources.dll'. The system cannot find the file specified.
Could not load file or assembly 'C:\GTARoleplay\server-files\dotnet\resources\GTARoleplay\netcoreapp3.1\Microsoft.EntityFrameworkCore.Relational.resources.dll'. The system cannot find the file specified.
Could not load file or assembly 'C:\GTARoleplay\server-files\dotnet\resources\GTARoleplay\netcoreapp3.1\Microsoft.EntityFrameworkCore.Relational.resources.dll'. The system cannot find the file specified.
FactionHandler: all factions have been loaded (0)`

I can join the game, saw the message Welcome to GTARoleplay but it looks like i am at freeroam because there are nothing. The char just spawns bold =(

Can you help me on what i am missing, please?
ty!

**Comment by schlembo** [comment]
Same on my try to install the server. I copied `Microsoft.EntityFrameworkCore.dll` to `Microsoft.EntityFrameworkCore.resources.dll` and `Microsoft.EntityFrameworkCore.Relational.dll` to `Microsoft.EntityFrameworkCore.Relational.resources.dll` and the error message are gone.

But as u say i can join and it says `Welcome to GTARoleplay` but no more happen.

**Comment by Andreas1331** [comment]
Right I must have forgotten to mention that the NuGet dependencies must be copied to the folder ```dotnet\runtime```. You can find the .DLL files inside the build folder at ```dotnet\resources\GTARoleplay\netcoreapp3.1```.

If nothing shows up after you fix the missing depedencies try to look at your ```client_packages/index.js``` and make sure it contains the 'include' needed for the client files.
```
require('gtaroleplay/index.js');
```

**Comment by Bullsito** [comment]
Hi, I'm getting the same problem, when I copy/paste those files the console says they can't find other files. (for example, Microsoft.Extensions.DependencyInjection).

Did I miss something in the set-up?

**Comment by Andreas1331** [comment]
I have added xcopy post build events to move all the dependencies automatically into the specified server folder. This should no longer be an issue.
