### ISSUE TITLE
Server finds 1 script file

### ISSUE THREAD

**Issue by Gustopop** [Andreas1331/ragemp-roleplay#2]
Hi! I am writing this in good faith. I followed every step from your README and I want some clarifications.
I created the MySQL server, after Add-Mitigation , I get a 
`No DbContext was found in assembly 'GTARoleplay'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.` 
Build starts and is succeded , but this is thrown after `add-migration InitialCreate` (I did set the server name, user, pass, port etc)

The GTARoleplay.dll path is not the correct one as VS is building a `GTARoleplay/obj/Debug/netcoreapp3.1/GTARoleplay.dll` but the server is set to access it from `./GTARoleplay/netcoreapp3.1` folder 

After managing to modify all these informations, the Solution builds successfully but after starting `rage-mp server` , it finds only one script file . Connecting to the server will spawn me in front of a ?church idk? with a bald character, no scripts running. 

Either I missed a step or did it wrong, but starting the server with no errors and with only 1 script is still confusing. 

I kindly ask you for some help to get this running or review and edit the instructions to set this up in a more in-depth, step by step way 🙏

**Comment by Andreas1331** [comment]
I have updated the readme and the project to be easier to setup, but in regards to Visual Studio saying no DbContext found it sounds like you haven't chosen the correct project to invoke the command against.
When you open the npm console there is a dropdown top right corner where you can select which VS proejct to use. Let me know.
