### ISSUE TITLE
GTANetworkAPI

### ISSUE THREAD

**Issue by Xlithan** [Andreas1331/ragemp-roleplay#3]
I had to add this API as it was missing (Wasn't suggested in the readme for some reason). I'm getting errors with this:
![image](https://github.com/Andreas1331/ragemp-roleplay/assets/66184380/843d6d0c-eb12-4d74-bc14-3dad1ad5c32a)

Any ideas? I also couldn't populate the database with the package manager console, it just said failed.

**Comment by Andreas1331** [comment]
Here I am a bit too late.
But it looks like you are missing a reference to the Rage API. I must have forgotten to mentioned that in the Readme. 
Go inside Visual Studio, expand your GTARoleplay project -> right click Dependencies -> Add reference -> Browse -> Then bottom right corner Browse again -> Navigate to YOUR_RAGE_FOLDER_PATH\server-files\dotnet\runtime\Bootstrapper.dll

Then the project will have the reference it needs.
