### ISSUE TITLE
namespace named player

### ISSUE THREAD

**Issue by dudulitrin** [Andreas1331/ragemp-roleplay#4]
i have this errors and idk what to do. i add the bootstrapp.dll but not solving my problem
![err](https://github.com/Andreas1331/ragemp-roleplay/assets/23567152/ac7a5024-0316-4c14-9b6a-ede4bea2f587)
![error](https://github.com/Andreas1331/ragemp-roleplay/assets/23567152/54d2e170-b180-472f-9601-17ee4c81c50c)

**Comment by Andreas1331** [comment]
Are you building for netcore 3.1?
Right click the project, select properties, then application and see the target framework.

And make sure the dependency for RageMP bootstrapper is added to the project. This is something I've left out of the readme I realise.

**Comment by Andreas1331** [comment]
added ragemp as nuget depdency, so no need to manually select the path.
Open a new issue if you continue having issues.
